language: java
before_cache:
- rm -rf $HOME/.m2/repository/com/github/zhanhb/thymeleaf-layout-dialect
- find $HOME/.m2/ -type d -name '*-SNAPSHOT' -exec rm -rf {} \; 2>/dev/null
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
install: mvn deploy -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.deploy.skip=true -B -V
script:
- mvn install -Dmaven.javadoc.skip=true
- jdk_switcher use oraclejdk7 && mvn -Djava.version=1.7 surefire:test
after_success:
- bash <(curl -s https://codecov.io/bash)
- jdk_switcher use oraclejdk8 && source .travis/publish.sh
