language: java
before_cache:
  - rm -rf $HOME/.m2/repository/com/github/zhanhb/thymeleaf-layout-dialect
cache:
  directories:
    - $HOME/.m2
jdk:
 - oraclejdk8
install: true
script:
  - mvn install -Dmaven.javadoc.skip=true
  - jdk_switcher use oraclejdk7 && mvn -Djava.version=1.7 surefire:test
