language: java
before_cache:
- rm -rf $HOME/.m2/repository/com/github/zhanhb/thymeleaf-layout-dialect
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
install: true
script:
- mvn install -Dmaven.javadoc.skip=true
- jdk_switcher use oraclejdk7 && mvn -Djava.version=1.7 surefire:test
after_success:
- bash <(curl -s https://codecov.io/bash)
- chmod +x .travis/publish.sh
- jdk_switcher use oraclejdk8 && .travis/publish.sh
- store build cache
env:
  global:
  - secure: MnRk6WkpdRg2TZSFUAIRXRSG0Ixd05QpXqzUor6Mw6xmYejOJbkkr/wy20080gr8HVSykY3sOw2rcrTPWyWiwHYjz2wAjXhhZebzYTdzicHOwHK8LaSa10O+/fuCEGRFxFP/pA3L7X9kgzq7EYVbGfFfOniOtT1TSWXeZNpmxcTNNYqpj7TjvL/dSI70XR9tzKru1fWTSQyitg8bi4vyx9QyAeqLV5ptkd9gjDNwm9RZuGv227CDAHJtWUwKGoTtUQz4o+hNJO8L/+hVEK3/ISWKcM0WmQRKaYQoMWzhYDei/a7htAasDhdcwQTPYNF9uM2adnE4Ws+HjUSKXdOEt6PD4wGzILvJ91P4VTK7g38k47egkT9L+4vtNqWEhNSfSuEM+0m4/AQpsg1vczdFKx3KpD5Ix19HJA2CPckaSYBbQbsM67Vb5Bb1IGDtpcdb43hkpFNLpvGztnaIjUCC/e5VkDdL9xnucaHJruH+aWlaJH+RjyX379xjwxPpoKrapCNbXtWaz7M7jg2hv/1/ZMbTBzD+sPhFfthw2jWdWRLlq5zMNedkzqpuDdmkCa0uhu/uAHoEA6Hxh8TfpeFPIMZnXT5jI7XFGxDKETaq9r71MFx+Jkl6zYck+FfoIFbm12RsY9duRVSonFjM1ny0yhS/wODxcorUl8pSW3ccq/s=
  - secure: Yqt5taJx3Xl7xJjKlxf8U5KtDIeujBiVBHeH1yg0njFQuIhSNNg2gMjA3iDDtpk9G2Zbz/o3TJ+gdQrzOaMYLj+iAlUaZMV2W/yfS6rcgJKgNIP0DsnWdAAJbjjnCLUERyogggXbIxySqtOiWJINkpm+Fd1jZOVxvTKAAykWYkiJufIVDYu5+Hria5PehF2XucpuxKEDmHBj0+0rP0fwGtF7SzyBQsAW7S8+N4t8kksOh3o6EJSVTDFQoG2f6oRiue0KLk0yUTXGoQ7zSL9m0ITGiG5+apc/F+Lewrh9IRygwXVKIT2qHJByqOot0a1MiuAsBA04pdvIm8fL52+/pOpYoxnDQJM9npFpUPPzIkc2EXopavkwCxz6EHKGLoKXRzyfYkMC3Ni8nDmqf9Mn7U+nkLIzOG5PLD4KbyKo9hN6bVcseYk3NaB+W+k09w9V0WFgMCJmsaBdl1OTzI4EPZqoals5cTpf/es2kZnA5AMi9qDIYUcA7hF1Lj1yK8sGQCyzuq0+ipa5geaOBQzb/R8A+hu4XyOym/dVOQs3MNsnoQRDiCmTasdH6X3w8byZAr3ovkuKyNP22ZAZkdx/lI+qi8gT3pei7jNbeQh7scomR3klBZexwq3lgNAjaCoW63O6meqXu9T/4pEZIRU7CrgyL1pxXAL9EPUb1AJSlI8=
